-- Permission rows were derived from the HTTP router and are regenerated by
-- `pnpm seed:initial-scripts:create-permission`; nothing in them is worth
-- migrating. Clearing first lets the new NOT NULL columns land without defaults.
-- The implicit _PermissionToRole join rows cascade with the permission rows.
DELETE FROM "Permission";

-- AlterTable
ALTER TABLE "Permission" DROP COLUMN "method",
DROP COLUMN "module",
DROP COLUMN "name",
DROP COLUMN "path",
ADD COLUMN     "action" VARCHAR(50) NOT NULL,
ADD COLUMN     "key" VARCHAR(200) NOT NULL,
ADD COLUMN     "resource" VARCHAR(100) NOT NULL,
ADD COLUMN     "scope" VARCHAR(10) NOT NULL;

-- AlterTable
ALTER TABLE "Role" ADD COLUMN     "isSystem" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE UNIQUE INDEX "Permission_key_key" ON "Permission"("key");

-- CreateIndex
CREATE INDEX "Permission_resource_action_idx" ON "Permission"("resource", "action");

