/**
 * Brand, category, product and their translation rows.
 *
 * Every entity gets its own `*_NOT_FOUND` rather than one shared
 * `RESOURCE_NOT_FOUND` plus a field: a client that has to parse a field to know
 * what went missing is branching on prose again, which is the thing codes exist
 * to stop.
 */
export const CatalogErrorCode = {
  BRAND_NOT_FOUND: "BRAND_NOT_FOUND",
  BRAND_ALREADY_EXISTS: "BRAND_ALREADY_EXISTS",
  BRAND_TRANSLATION_NOT_FOUND: "BRAND_TRANSLATION_NOT_FOUND",
  BRAND_TRANSLATION_ALREADY_EXISTS: "BRAND_TRANSLATION_ALREADY_EXISTS",

  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
  CATEGORY_TRANSLATION_NOT_FOUND: "CATEGORY_TRANSLATION_NOT_FOUND",
  CATEGORY_TRANSLATION_ALREADY_EXISTS: "CATEGORY_TRANSLATION_ALREADY_EXISTS",
  /** A category was pointed at itself as its parent. */
  CATEGORY_PARENT_SELF_REFERENCE: "CATEGORY_PARENT_SELF_REFERENCE",

  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_ALREADY_EXISTS: "PRODUCT_ALREADY_EXISTS",
  PRODUCT_TRANSLATION_NOT_FOUND: "PRODUCT_TRANSLATION_NOT_FOUND",
  PRODUCT_TRANSLATION_ALREADY_EXISTS: "PRODUCT_TRANSLATION_ALREADY_EXISTS",
  /** The caller is not the owner of the product it tried to manage. */
  PRODUCT_FORBIDDEN: "PRODUCT_FORBIDDEN",

  /** A supplied translation id does not resolve to a live row. */
  TRANSLATION_REFERENCE_INVALID: "TRANSLATION_REFERENCE_INVALID",
  SKU_NOT_FOUND: "SKU_NOT_FOUND",

  LANGUAGE_NOT_FOUND: "LANGUAGE_NOT_FOUND",
  LANGUAGE_ALREADY_EXISTS: "LANGUAGE_ALREADY_EXISTS",
} as const;
