name: CI

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Generate Prisma client
        shell: bash
        run: pnpm prisma:generate

      - name: Lint
        shell: bash
        run: pnpm lint

  # types-check:
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.draft == false

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install dependencies
  #       uses: ./.github/actions/pnpm-install

  #     - name: Types check
  #       shell: bash
  #       run: pnpm types-check

  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Build
        shell: bash
        run: pnpm build
